# Generated by Django 2.2.1 on 2019-06-04 10:50

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='2019', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1', 'SPRING'), ('2', 'SUMMER'), ('3', 'AUTUMN'), ('4', 'WINTER')], default='1', max_length=4)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Year')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', tinymce.models.HTMLField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='article.Season')),
            ],
        ),
    ]
