# Generated by Django 2.2.1 on 2019-06-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(choices=[('spr', 'SPRING'), ('sum', 'SUMMER'), ('aut', 'AUTUMN'), ('win', 'WINTER')], default='1', max_length=4),
        ),
        migrations.AlterField(
            model_name='year',
            name='name',
            field=models.CharField(choices=[('19', '2019'), ('20', '2020'), ('21', '2021'), ('22', '2022'), ('23', '2023'), ('24', '2024'), ('25', '2025')], default='2019', max_length=4),
        ),
    ]
