# Generated by Django 2.2.1 on 2019-06-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190604_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='제목쓰셈', max_length=12),
        ),
    ]
