# Generated by Django 2.2.1 on 2019-06-14 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='explain_in_1_line',
            field=models.CharField(default='당당하기만 하면 된다.', max_length=100),
        ),
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(choices=[('spr', '봄'), ('sum', '여름'), ('aut', '가을'), ('win', '겨울')], default='1', max_length=4),
        ),
        migrations.AlterField(
            model_name='season',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='article.Year'),
        ),
    ]
