# Generated by Django 2.2.1 on 2019-06-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20190614_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='null', max_length=12),
        ),
        migrations.AlterField(
            model_name='season',
            name='explain_in_1_line',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(blank=True, choices=[('spr', '봄'), ('sum', '여름'), ('aut', '가을'), ('win', '겨울')], default='', max_length=4),
        ),
    ]
