# Generated by Django 2.2.1 on 2019-06-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20190614_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='explain_in_1_line',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(choices=[('spr', '봄'), ('sum', '여름'), ('aut', '가을'), ('win', '겨울')], default='', max_length=4),
        ),
    ]
