# Generated by Django 2.2.1 on 2019-06-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20190614_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(default='새 시즌', max_length=40),
        ),
    ]
